name: Snowflake CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Snowflake CLI
        run: pip install snowflake-cli-labs

      - name: Deploy SQL
        env:
           SNOWFLAKE_CONNECTIONS_FC_ACCOUNT: ${{ secrets.ACCOUNT }}
           SNOWFLAKE_CONNECTIONS_FC_USER: ${{ secrets.USER }}
           SNOWFLAKE_CONNECTIONS_FC_PASSWORD: ${{ secrets.PASSWORD }}
           SNOWFLAKE_CONNECTIONS_FC_WAREHOUSE: ${{ secrets.WAREHOUSE }}
           SNOWFLAKE_CONNECTIONS_FC_DATABASE: ${{ secrets.DATABASE }}
           SNOWFLAKE_CONNECTIONS_FC_SCHEMA: ${{ secrets.SCHEMA }}
        run: |
          snow connection test --connection fc
          snow run deploy_all --connection fc

